"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# CONFIGURACIÓN DE SEGURIDAD (Variables de Entorno)
# ==============================================================================
SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)

# Leemos los hosts de la variable; si no existe, cae en el subdominio del Grupo 4
ALLOWED_HOSTS = config(
    'DJANGO_ALLOWED_HOSTS', 
    default='api.app4.academia.ar,localhost,127.0.0.1'
).split(',')

# ==============================================================================
# DEFINICIÓN DE APLICACIONES Y MIDDLEWARES
# ==============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps de terceros
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    # Apps locales
    'portfolio',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Debe estar lo más arriba posible
    'django.middleware.security.SecurityMiddleware',         
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',             
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ==============================================================================
# CONFIGURACIÓN DE BASE DE DATOS (Mapeo Híbrido SQLite / PostgreSQL)
# ==============================================================================
# Si en el entorno existe DATABASE_URL (Docker/Producción), se conecta a Postgres.
# Si estás desarrollando local sin esa variable, usa el SQLite de siempre para no romper tu flujo.
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ==============================================================================
# VALIDACIÓN DE CONTRASEÑAS
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ==============================================================================
# INTERNACIONALIZACIÓN
# ==============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# ARCHIVOS ESTÁTICOS (Para Producción)
# ==============================================================================
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ==============================================================================
# CONFIGURACIÓN DE SEGURIDAD DJANGO REST FRAMEWORK & JWT
# ==============================================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# Corregido: Agregamos firma dinámica usando una clave JWT dedicada para encriptar contraseñas/tokens
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'SIGNING_KEY': config('JWT_SECRET_KEY', default=SECRET_KEY),
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ==============================================================================
# CONFIGURACIÓN DE CORS & CSRF PREMIUM (Grupo 4)
# ==============================================================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://app4.academia.ar",
]

CSRF_TRUSTED_ORIGINS = [
    "https://app4.academia.ar",
    "https://api.app4.academia.ar",
    "http://localhost:5173",
]

CORS_ALLOW_CREDENTIALS = True