# Generated by Django 6.0.5 on 2026-05-30 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_total_value_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='position',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.portfolio')),
            ],
        ),
        migrations.RemoveField(
            model_name='position',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='position',
            name='updated_at',
        ),
    ]
