# Generated by Django 6.0.5 on 2026-05-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_position_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=15),
        ),
    ]
